version: '3.8'

services:

  web:
    restart: unless-stopped
    build: 
      context: ./app
      dockerfile: Dockerfile.dev
    command: 
      'python manage.py runserver 0.0.0.0:8000'    # development
    volumes:
      - ./app:/usr/src/app/
      - mediafiles:/home/app/web/mediafiles


    ports:
      - '8000:8000'
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    restart: unless-stopped
    image: 'postgres:15'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data/'
    ports:
      - '5432:5432'
    env_file:
      - ./.env.dev.db

volumes:
  postgres_data: null
  mediafiles: null
